### ISSUE TITLE
yarn安装提示问题

### ISSUE THREAD

**Issue by Leader755** [lanpangzhi/novel-vue#10]
![image](https://user-images.githubusercontent.com/37180494/63826540-15d1f400-c992-11e9-9474-0f4f0a551064.png)
大佬，求解下，这是包安装不兼容么，家里的电脑会出现这提示，公司这正常运行。出现这提示，就不能运行。能给解决方法么，网上没搜到。

**Comment by lanpangzhi** [comment]
警告可以不用管  npm config set puppeteer_download_host https://cdn.npm.taobao.org/dist

**Comment by Leader755** [comment]
问题是运行不了

**Comment by lanpangzhi** [comment]
npm config set puppeteer_download_host https://cdn.npm.taobao.org/dist

**Comment by Leader755** [comment]
我回去试下，感谢

**Comment by Leader755** [comment]
算了，我放弃了，我换别的，搞了3天，还是运行不起来。我去找别的例子。
