### ISSUE TITLE
我无法运行

### ISSUE THREAD

**Issue by Leader755** [lanpangzhi/novel-vue#8]
大佬，请问下，代码没问题吧，我用yarn运行报错。我之前一般用cnpm，请大佬指教。

**Comment by lanpangzhi** [comment]
上报错截图

**Comment by Leader755** [comment]
感谢大佬的及时回复，刚在公司电脑运行起来了。晚上回家我再试试，昨晚使用yarn出现一堆问题，那应该是yarn使用时出现的问题。再次感谢大佬的及时回复。我会按照demo，将自动生成的骨架屏应用到项目上的，感谢大佬.
