### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by Leader755** [lanpangzhi/novel-vue#9]
开发模式下是看不到骨架屏的吧，使用按钮无效报错。打包后看到了骨架屏，但是只是限于首页，这是基于dom自动生成的么？还是手写的，另外一个页面我没有看到。
![11](https://user-images.githubusercontent.com/37180494/63742311-13589700-c8cb-11e9-8e81-9b38663238dc.gif)
![12](https://user-images.githubusercontent.com/37180494/63742323-19e70e80-c8cb-11e9-84e4-eafa7a646ade.gif)

请大佬指教，谢谢。

**Comment by lanpangzhi** [comment]
配置的  看vue.config.js 文件
